Repository cloud-native-toolkit/image-cli-tools-core, pull requests merged in 2022-08, with the labels that each got.

#13 Adds htpasswd cli to the image
  .github/workflows/docker-build.yaml
  Containerfile
  Containerfile-alpine
  Containerfile-fedora
  Dockerfile
  README.md
Labels: feature, minor

#14 Update igc and gitu clis
  Containerfile-alpine
  Containerfile-fedora
Labels: bug, patch

#15 Installs igc plugins into oc/kubectl cli
  Containerfile-alpine
  Containerfile-fedora
Labels: bug, patch

#18 Adds tkn to image and updates igc and gitu
  Containerfile-alpine
  Containerfile-fedora
Labels: feature, minor

#19 Updates igc cli to v1.38.1 to fix endpoints command
  Containerfile-alpine
  Containerfile-fedora
Labels: bug, patch

#21 Updates notification workflows
  .github/workflows/docker-build.yaml
  .github/workflows/update-base-image.yaml
Labels: chore, patch

#22 Updates cloud-native-toolkit/image-terraform module to v2.0.5
  Containerfile-alpine
  Containerfile-fedora
Labels: bug, patch

#23 Updates cloud-native-toolkit/image-terraform module to v2.0.6
  Containerfile-alpine
  Containerfile-fedora
Labels: bug, patch

#24 Updates cloud-native-toolkit/image-terraform module to v2.0.7
  Containerfile-alpine
  Containerfile-fedora
Labels: bug, patch
