Repository cloud-native-toolkit/image-cli-tools-core, pull requests merged in 2025-03, with the labels that each got.

#43 Updates cloud-native-toolkit/image-terraform module to v4.0.0
  Containerfile-alpine
  Containerfile-fedora
Labels: feature, minor

#44 Update base image and cli versions
  .github/workflows/docker-build.yaml
  Containerfile-alpine
  Containerfile-fedora
  src/home/image-message
Labels: enhancement, major

#45 Replace deprecated calls in workflow
  .github/workflows/docker-build.yaml
Labels: chore, patch

#46 Updates cloud-native-toolkit/image-terraform module to v4.0.1
  Containerfile-alpine
  Containerfile-fedora
Labels: bug, patch

#47 Updates cloud-native-toolkit/image-terraform module to v4.0.2
  Containerfile-alpine
  Containerfile-fedora
Labels: bug, patch
